version: '3.9'
name: krakend-api-gateway

services:
  endpoint_1:
    container_name: endpoint1
    build: ./endpoint/
    ports:
      - "5001:3001"
    environment:
      - ENDPOINT_VERSION=1
      - PORT_NUMBER=3001
    networks:
      - krakend

  endpoint_2:
    container_name: endpoint2
    build: ./endpoint/
    ports:
      - "5002:3002"
    environment:
      - ENDPOINT_VERSION=2
      - PORT_NUMBER=3002
    networks:
      - krakend
      
  endpoint_3:
    container_name: endpoint3
    build: ./endpoint/
    ports:
      - "5003:3003"
    environment:
      - ENDPOINT_VERSION=3
      - PORT_NUMBER=3003
    networks:
      - krakend

  krakend-gateway:
    container_name: krakend-gateway
    image: devopsfaith/krakend
    ports:
      - 8080:8080
    volumes:
      - ./krakend/:/etc/krakend/
    command: ["run", "--config", "/etc/krakend/krakend.json"]
    networks:
      - krakend

networks:
  krakend: